### ISSUE TITLE
Not installable with vagrant plugin install on Ubuntu 18.04 beta 1

### ISSUE THREAD

**Issue by russianlagman** [devopsgroup-io/vagrant-hostmanager#256]
```
bigboss@bigboss:~/Work/project$ vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 1.45.0)
  Activated fog-core-1.45.0
  which does not match conflicting dependency (~> 1.43.0)

  Conflicting dependency chains:
    fog-core (= 1.45.0), 1.45.0 activated

  versus:
    vagrant-libvirt (> 0), 0.0.41 activated, depends on
    fog-core (~> 1.43.0)

bigboss@bigboss:~/Work/affstats$ vagrant -v
Vagrant 2.0.2
```

**Comment by purencool** [comment]
I can confirm this issue

**Comment by daniel361** [comment]
+1

**Comment by russianlagman** [comment]
Issue is simple, vagrant-libvirt installed with vagrant on 18.04 has version 1.45.0. Version 1.43.0 is not available for this distro.

**Comment by amartyniuk** [comment]
So what's the fix?

**Comment by Potherca** [comment]
I had a similar problem that was resolved when I updated to Vagrant `v2.0.3 `:

```
wget -c https://releases.hashicorp.com/vagrant/2.0.3/vagrant_2.0.3_x86_64.deb
sudo dpkg -i vagrant_2.0.3_x86_64.deb
```

(I have not yet tried with `v2.0.4`)

**Comment by quangthe** [comment]
@Potherca Thanks! It works for me as well.

**Comment by lucasifto** [comment]
@Potherca works for me too...tanks

**Comment by ThomasG77** [comment]
I can confirm the recipe with version 2.0.4 works e.g

    wget -c https://releases.hashicorp.com/vagrant/2.0.4/vagrant_2.0.4_x86_64.deb
    sudo dpkg -i vagrant_2.0.4_x86_64.deb

**Comment by macduff23** [comment]
likewise im getting this with 2.4 on ubuntu 19'ish, is there a fix besides reverting to an older vagrant package? ~ Installing the 'vagrant-lxd' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 2.1.0)
  Activated fog-core-2.1.0
  which does not match conflicting dependency (~> 1.43.0)

  Conflicting dependency chains:
    fog-core (= 2.1.0), 2.1.0 activated

  versus:
    vagrant-libvirt (> 0), 0.0.41 activated, depends on
    fog-core (~> 1.43.0)
root@xxxx:/home/vagrant# vagrant -v
Vagrant 2.2.3

**Comment by russianlagman** [comment]
Got the same issue on 19.10 ubuntu.
The only solution is to get latest .deb package from the vagrant official site and to install it manualy.

**Comment by ydutta-cpi** [comment]
Try "vagrant plugin update"
